language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t devvyky/react-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true devvyky/react-app npm test

after_success:
  - docker build -t devvyky/multi-client ./client
  - docker build -t devvyky/multi-nginx ./nginx
  - docker build -t devvyky/multi-server ./server
  - docker build -t devvyky/multi-worker ./worker
