language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t devvyky/react-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true devvyky/react-app npm test

after_success:
  - docker build -t devvyky/multi-client ./client
  - docker build -t devvyky/multi-nginx ./nginx
  - docker build -t devvyky/multi-server ./server
  - docker build -t devvyky/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push devvyky/multi-client
  - docker push devvyky/multi-nginx
  - docker push devvyky/multi-server
  - docker push devvyky/multi-worker
